from src.guides.viz_callbacks import VizCallbackData


class GuideCallbackData(VizCallbackData):
    SELECT_VIZ = "guide:select:viz"
    SELECT_CITY_WALK = "guide:select:city_walk"
    SELECT_BIG_KONNY = "guide:select:big_konny"
    SELECT_CHEKISTS = "guide:select:chekists"
    CHEKISTS_NEXT = "guide:chekists:next"
    CHEKISTS_NEXT_AFTER_FIRST = "guide:chekists:next:1"
    CHEKISTS_NEXT_AFTER_SECOND = "guide:chekists:next:2"
    CHEKISTS_NEXT_AFTER_THIRD = "guide:chekists:next:3"
    CHEKISTS_NEXT_AFTER_FOURTH = "guide:chekists:next:4"
    CHEKISTS_NEXT_AFTER_FIFTH = "guide:chekists:next:5"
    CHEKISTS_NEXT_AFTER_SIXTH = "guide:chekists:next:6"
    CHEKISTS_NEXT_AFTER_SEVENTH = "guide:chekists:next:7"
    CHEKISTS_NEXT_AFTER_EIGHTH = "guide:chekists:next:8"
    CHEKISTS_NEXT_AFTER_NINTH = "guide:chekists:next:9"
    CHEKISTS_NEXT_AFTER_TENTH = "guide:chekists:next:10"
    CHEKISTS_NEXT_AFTER_TWELFTH = "guide:chekists:next:12"
    CHEKISTS_NEXT_AFTER_THIRTEENTH = "guide:chekists:next:13"
    CHEKISTS_NEXT_AFTER_FOURTEENTH = "guide:chekists:next:14"
    CHEKISTS_NEXT_AFTER_FIFTEENTH = "guide:chekists:next:15"
    CHEKISTS_NEXT_AFTER_SIXTEENTH = "guide:chekists:next:16"
    CHEKISTS_NEXT_AFTER_SEVENTEENTH = "guide:chekists:next:17"
    CHEKISTS_NEXT_AFTER_EIGHTEENTH = "guide:chekists:next:18"
    CHEKISTS_NEXT_AFTER_NINETEENTH = "guide:chekists:next:19"
    CHEKISTS_NEXT_AFTER_TWENTIETH = "guide:chekists:next:20"
    CHEKISTS_NEXT_AFTER_TWENTY_FIRST = "guide:chekists:next:21"
    CHEKISTS_NEXT_AFTER_TWENTY_SECOND = "guide:chekists:next:22"
    CHEKISTS_NEXT_AFTER_TWENTY_THIRD = "guide:chekists:next:23"
    CHEKISTS_NEXT_AFTER_TWENTY_FOURTH = "guide:chekists:next:24"
    CHEKISTS_NEXT_AFTER_TWENTY_FIFTH = "guide:chekists:next:25"
    CHEKISTS_NEXT_AFTER_TWENTY_SIXTH = "guide:chekists:next:26"
    CHEKISTS_NEXT_AFTER_TWENTY_SEVENTH = "guide:chekists:next:27"
    CHEKISTS_NEXT_AFTER_TWENTY_EIGHTH = "guide:chekists:next:28"
    CHEKISTS_NEXT_AFTER_TWENTY_NINTH = "guide:chekists:next:29"
    CHEKISTS_NEXT_AFTER_THIRTIETH = "guide:chekists:next:30"
    CHEKISTS_NEXT_AFTER_THIRTY_FIRST = "guide:chekists:next:31"
    CHEKISTS_NEXT_AFTER_THIRTY_SECOND = "guide:chekists:next:32"
    CHEKISTS_NEXT_AFTER_THIRTY_THIRD = "guide:chekists:next:33"
    CHEKISTS_NEXT_AFTER_THIRTY_FOURTH = "guide:chekists:next:34"
    FINISH_CHEKISTS = "guide:chekists:finish"
    CHEKISTS_FIND_ALL_IDOLS = "guide:chekists:idols:find_all"
