class GuideCallbackData:
    SELECT_VIZ = "guide:select:viz"
    SELECT_BIG_KONNY = "guide:select:big_konny"
    CHECK_VIZ_PAYMENT = "guide:viz:payment:check"
    VIZ_NEXT = "guide:viz:next"
    VIZ_NEXT_AFTER_SECOND = "guide:viz:next:2"
    VIZ_NEXT_AFTER_THIRD = "guide:viz:next:3"
    VIZ_NEXT_AFTER_FOURTH = "guide:viz:next:4"
    VIZ_NEXT_AFTER_FIFTH = "guide:viz:next:5"
    VIZ_NEXT_AFTER_SIXTH = "guide:viz:next:6"
    VIZ_NEXT_AFTER_SEVENTH = "guide:viz:next:7"
    VIZ_NEXT_AFTER_EIGHTH = "guide:viz:next:8"
    VIZ_NEXT_AFTER_NINTH = "guide:viz:next:9"
