CHEKISTS_FIRST_POST_NUMBER = 301
CHEKISTS_SECOND_POST_NUMBER = 302
CHEKISTS_THIRD_POST_NUMBER = 303
CHEKISTS_FOURTH_POST_NUMBER = 304
CHEKISTS_FIFTH_POST_NUMBER = 305
CHEKISTS_SIXTH_POST_NUMBER = 306
CHEKISTS_SEVENTH_POST_NUMBER = 307
CHEKISTS_EIGHTH_POST_NUMBER = 308
CHEKISTS_NINTH_POST_NUMBER = 309
CHEKISTS_TENTH_POST_NUMBER = 310
CHEKISTS_ELEVENTH_POST_NUMBER = 311
CHEKISTS_TWELFTH_POST_NUMBER = 312
CHEKISTS_THIRTEENTH_POST_NUMBER = 313
CHEKISTS_FOURTEENTH_POST_NUMBER = 314
CHEKISTS_FIFTEENTH_POST_NUMBER = 315
CHEKISTS_SIXTEENTH_POST_NUMBER = 316
CHEKISTS_SEVENTEENTH_POST_NUMBER = 317
CHEKISTS_EIGHTEENTH_POST_NUMBER = 318
CHEKISTS_NINETEENTH_POST_NUMBER = 319
CHEKISTS_TWENTIETH_POST_NUMBER = 320
CHEKISTS_TWENTY_FIRST_POST_NUMBER = 321
CHEKISTS_TWENTY_SECOND_POST_NUMBER = 322
CHEKISTS_TWENTY_THIRD_POST_NUMBER = 323
CHEKISTS_TWENTY_FOURTH_POST_NUMBER = 324

DEFAULT_CHEKISTS_FIRST_POST = (
    "*Старт*\n\n"
    "Городок чекистов — это комплекс зданий в стиле конструктивизма. "
    "Его построили в 1929–1936 года.\n\n"
    "Вокруг него ходят десятки легенд. В этой прогулке расскажу историю "
    "каждого корпуса, покажу интересные локации от кофеен до музеев "
    "и стрит-арт, который скрывается в уголках квартала.\n\n"
    "Я изучила публикации в СМИ, книгу, побывала на экскурсии у Игоря "
    "Янкова и прогуливалась сама несколько раз. Погнали вместе!"
)
