GUIDE_BIG_KONNY = "big_konny"
GUIDE_CHEKISTS = "chekists"
GUIDE_CITY_WALK = "city_walk"
GUIDE_VIZ = "viz"

DEFAULT_VISIBLE_GUIDES = {GUIDE_BIG_KONNY, GUIDE_CITY_WALK, GUIDE_VIZ}
ALL_GUIDES = {GUIDE_BIG_KONNY, GUIDE_CHEKISTS, GUIDE_CITY_WALK, GUIDE_VIZ}
